[tool.poetry]
name = "simple-guard"
version = "0.1.0"
description = ""
authors = ["Bastiaan Witte <bastiaan@foodticket.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
